---
- hosts: webserver
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull and run the Docker image for your Node.js app
      docker_container:
        name: blog-api
        image: your-dockerhub-username/blog-api:latest
        state: started
        ports:
          - "80:3000"
