name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.0'

    - name: Install dependencies
      run: npm install
      working-directory: blog-api  # Only use working-directory with run

    - name: Lint code
      run: npm run lint
      working-directory: blog-api  # Only use working-directory with run

    - name: Run unit tests
      run: npm test
      working-directory: blog-api  # Only use working-directory with run

    - name: Run security scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        project-directory: blog-api  # If Snyk supports project-directory, use this

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: blog-api  # Set context to blog-api directory
        file: blog-api/Dockerfile  # Ensure Dockerfile path is correct
        push: true
        tags: yourusername/blog-api:latest
